# Generated by Django 5.2.8 on 2025-11-27 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_historicaldepartment_historicalposition'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobtitle',
            name='description',
        ),
    ]
