# Generated by Django 5.2.8 on 2025-11-27 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0003_remove_jobtitle_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalposition',
            name='name',
        ),
        migrations.RemoveField(
            model_name='position',
            name='name',
        ),
    ]
