# Generated by Django 5.2.8 on 2025-11-27 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0004_remove_historicalposition_name_remove_position_name'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='position',
            unique_together={('department', 'job_title')},
        ),
    ]
