# Generated by Django 5.2.8 on 2025-11-28 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0005_alter_position_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalposition',
            name='manager_position',
        ),
        migrations.RemoveField(
            model_name='position',
            name='manager_position',
        ),
        migrations.AddField(
            model_name='position',
            name='manager_positions',
            field=models.ManyToManyField(blank=True, help_text='Posiciones a las que reporta directamente (Jefes Inmediatos).', related_name='direct_reports', to='organization.position'),
        ),
    ]
