# Generated by Django 5.2.8 on 2025-11-30 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0007_alter_department_name_alter_department_parent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalposition',
            name='objective',
            field=models.TextField(blank=True, help_text='Objetivo general del cargo', null=True, verbose_name='Objetivo'),
        ),
        migrations.AddField(
            model_name='position',
            name='objective',
            field=models.TextField(blank=True, help_text='Objetivo general del cargo', null=True, verbose_name='Objetivo'),
        ),
        migrations.DeleteModel(
            name='PositionObjective',
        ),
    ]
