# Generated by Django 5.2.8 on 2025-12-01 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0008_historicalposition_objective_position_objective_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalposition',
            name='is_manager',
            field=models.BooleanField(default=False, help_text='Indica si esta posición tiene responsabilidades gerenciales.', verbose_name='Es Gerencial'),
        ),
        migrations.AddField(
            model_name='position',
            name='is_manager',
            field=models.BooleanField(default=False, help_text='Indica si esta posición tiene responsabilidades gerenciales.', verbose_name='Es Gerencial'),
        ),
    ]
