# Generated by Django 5.2.8 on 2025-11-24 13:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre del Curso')),
                ('description', models.TextField(blank=True, null=True)),
                ('start_date', models.DateField(verbose_name='Fecha Inicio')),
                ('end_date', models.DateField(verbose_name='Fecha Fin')),
                ('modality', models.CharField(choices=[('PRE', 'Presencial'), ('VIR', 'Virtual (En Vivo / Zoom)'), ('ASY', 'Virtual (Autoaprendizaje)'), ('MIX', 'Híbrido / Mixto')], default='PRE', max_length=3)),
                ('max_participants', models.PositiveIntegerField(default=20, help_text='Límite de estudiantes permitidos.', verbose_name='Cupo Máximo')),
                ('duration_hours', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('BOR', 'Borrador'), ('PRO', 'Programado'), ('EJE', 'En Ejecución'), ('FIN', 'Finalizado'), ('CAN', 'Cancelado')], default='BOR', max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CourseParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('INS', 'Instructor'), ('EST', 'Estudiante')], default='EST', max_length=3)),
                ('status', models.CharField(choices=[('PEN', 'Pendiente'), ('APR', 'Aprobado'), ('REP', 'Reprobado'), ('RET', 'Retirado')], default='PEN', max_length=3)),
                ('grade', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='training.course')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_courses', to='core.person')),
            ],
            options={
                'unique_together': {('course', 'person')},
            },
        ),
        migrations.CreateModel(
            name='CourseResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Título del Recurso')),
                ('resource_type', models.CharField(choices=[('FIL', 'Archivo (PDF/Doc/Img)'), ('URL', 'Enlace Externo / Video')], default='FIL', max_length=3)),
                ('file', models.FileField(blank=True, null=True, upload_to='training/resources/')),
                ('url', models.URLField(blank=True, help_text='Youtube, Drive, Zoom, etc.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='training.course')),
            ],
        ),
        migrations.CreateModel(
            name='CourseSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=200, verbose_name='Tema / Título de la Sesión')),
                ('date', models.DateField(verbose_name='Fecha de la sesión')),
                ('start_time', models.TimeField(verbose_name='Hora Inicio')),
                ('end_time', models.TimeField(verbose_name='Hora Fin')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='training.course')),
            ],
            options={
                'ordering': ['date', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PRE', 'Presente'), ('AUS', 'Ausente'), ('TAR', 'Tardanza'), ('JUS', 'Justificado')], default='AUS', max_length=3)),
                ('notes', models.CharField(blank=True, max_length=255, null=True)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_history', to='training.courseparticipant')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='training.coursesession')),
            ],
            options={
                'unique_together': {('session', 'participant')},
            },
        ),
    ]
