# Generated by Django 5.2.8 on 2025-11-24 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseparticipant',
            name='status',
            field=models.CharField(choices=[('PEN', 'Pendiente'), ('APR', 'Aprobado'), ('REP', 'Reprobado'), ('INS', 'Inscrito'), ('RET', 'Retirado')], default='PEN', max_length=3),
        ),
    ]
