# Generated by Django 5.2.8 on 2025-11-25 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0004_alter_courseparticipant_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseparticipant',
            name='status',
            field=models.CharField(choices=[('SOL', 'Solicitud Enviada'), ('PEN', 'Pendiente'), ('APR', 'Aprobado'), ('REP', 'Reprobado'), ('INS', 'Inscrito'), ('RET', 'Retirado'), ('REJ', 'Solicitud Rechazada')], default='PEN', max_length=3),
        ),
    ]
