# Generated by Django 5.2.8 on 2025-11-26 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0005_alter_courseparticipant_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseparticipant',
            name='academic_status',
            field=models.CharField(choices=[('NEV', 'No Evaluado / N/A'), ('PEN', 'En Curso / Pendiente'), ('APR', 'Aprobado'), ('REP', 'Reprobado')], default='NEV', max_length=3, verbose_name='Estado Académico'),
        ),
        migrations.AddField(
            model_name='courseparticipant',
            name='enrollment_status',
            field=models.CharField(choices=[('REQ', 'Solicitud Enviada'), ('ENR', 'Inscrito / Matriculado'), ('REJ', 'Solicitud Rechazada'), ('DRP', 'Retirado')], default='REQ', max_length=3, verbose_name='Estado de Inscripción'),
        ),
        migrations.AlterField(
            model_name='courseparticipant',
            name='status',
            field=models.CharField(choices=[('SOL', 'Solicitud Enviada'), ('PEN', 'Pendiente'), ('APR', 'Aprobado'), ('REP', 'Reprobado'), ('INS', 'Inscrito'), ('RET', 'Retirado'), ('REJ', 'Solicitud Rechazada')], default='PEN', max_length=3, null=True),
        ),
    ]
