# Generated by Django 5.2.8 on 2025-11-26 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0007_auto_20251126_1037'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courseparticipant',
            name='status',
        ),
    ]
