# Generated by Django 5.2.8 on 2025-12-02 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0009_course_is_public_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseparticipant',
            name='academic_status',
            field=models.CharField(choices=[('PEN', 'En Curso'), ('APR', 'Aprobado'), ('REP', 'Reprobado')], default='PEN', max_length=3, verbose_name='Estado Académico'),
        ),
        migrations.AlterField(
            model_name='courseparticipant',
            name='enrollment_status',
            field=models.CharField(choices=[('REQ', 'Solicitud Enviada'), ('ENR', 'Inscrito'), ('REJ', 'Solicitud Rechazada')], default='REQ', max_length=3, verbose_name='Estado de Inscripción'),
        ),
    ]
