# Generated by Django 5.2.8 on 2025-12-02 22:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0014_courseparticipant_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='requires_approval_to_complete',
            field=models.BooleanField(default=False, help_text='Si es True, el instructor debe asignar nota manualmente. Si es False, se completa automáticamente al terminar todas las lecciones.', verbose_name='Requiere Aprobación Manual'),
        ),
        migrations.AlterField(
            model_name='courseparticipant',
            name='academic_status',
            field=models.CharField(choices=[('PEN', 'En Curso'), ('COM', 'Completado'), ('APR', 'Aprobado'), ('REP', 'Reprobado')], default='PEN', max_length=3, verbose_name='Estado Académico'),
        ),
        migrations.CreateModel(
            name='CourseModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre del Módulo')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='training.course')),
            ],
            options={
                'verbose_name': 'Módulo del Curso',
                'verbose_name_plural': 'Módulos del Curso',
                'ordering': ['order'],
                'unique_together': {('course', 'order')},
            },
        ),
        migrations.CreateModel(
            name='CourseLesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título de la Lección')),
                ('content', models.TextField(help_text='Contenido en formato de texto enriquecido', verbose_name='Contenido')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('duration_minutes', models.PositiveIntegerField(default=0, verbose_name='Duración (minutos)')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='training.coursemodule')),
            ],
            options={
                'verbose_name': 'Lección',
                'verbose_name_plural': 'Lecciones',
                'ordering': ['order'],
                'unique_together': {('module', 'order')},
            },
        ),
        migrations.CreateModel(
            name='LessonProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed', models.BooleanField(default=False, verbose_name='Completada')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Completitud')),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_progress', to='training.courseparticipant')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_records', to='training.courselesson')),
            ],
            options={
                'verbose_name': 'Progreso de Lección',
                'verbose_name_plural': 'Progreso de Lecciones',
                'unique_together': {('enrollment', 'lesson')},
            },
        ),
    ]
