# Generated by Django 5.2.8 on 2025-12-02 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0015_course_requires_approval_to_complete_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='courselesson',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='training/lessons/', verbose_name='Archivo Adjunto'),
        ),
        migrations.AddField(
            model_name='courselesson',
            name='url',
            field=models.URLField(blank=True, help_text='Video de Youtube, Zoom, etc.', null=True, verbose_name='Enlace Externo'),
        ),
        migrations.AlterField(
            model_name='courselesson',
            name='content',
            field=models.TextField(blank=True, help_text='Contenido en formato de texto enriquecido', null=True, verbose_name='Contenido'),
        ),
    ]
