# Generated by Django 5.2.8 on 2025-12-03 00:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0016_courselesson_file_courselesson_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courselesson',
            name='file',
        ),
        migrations.RemoveField(
            model_name='courselesson',
            name='url',
        ),
        migrations.AddField(
            model_name='courseresource',
            name='lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='training.courselesson'),
        ),
    ]
