# Generated by Django 5.2.8 on 2025-12-01 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_historicalperson_birthdate'),
        ('talent', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personlanguage',
            name='reading_proficiency',
        ),
        migrations.AddConstraint(
            model_name='personlanguage',
            constraint=models.UniqueConstraint(fields=('person', 'language'), name='unique_person_language', violation_error_message='Esta persona ya tiene registrado este idioma.'),
        ),
    ]
