# Generated by Django 5.2.8 on 2025-12-01 21:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talent', '0002_remove_personlanguage_reading_proficiency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='personlanguage',
            name='reading_proficiency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reading', to='talent.languageproficiency'),
        ),
    ]
