# Generated by Django 5.2.8 on 2025-12-07 05:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talent', '0003_personlanguage_reading_proficiency'),
    ]

    operations = [
        migrations.AddField(
            model_name='fieldofstudy',
            name='education_level',
            field=models.ForeignKey(blank=True, help_text='Nivel educativo al que pertenece este campo de estudio', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fields_of_study', to='talent.educationlevel'),
        ),
        migrations.AlterField(
            model_name='fieldofstudy',
            name='name',
            field=models.CharField(error_messages={'unique': 'Ya existe un registro con este nombre.'}, help_text='Ej: Software, Recursos Humanos, Diseño Gráfico', max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='fieldofstudy',
            unique_together={('education_level', 'name')},
        ),
    ]
