# Generated by Django 5.2.8 on 2025-11-25 06:08

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('employment', '0001_initial'),
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvaluationPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('start_date', models.DateField(verbose_name='Inicio')),
                ('end_date', models.DateField(verbose_name='Cierre')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Periodo de Evaluación',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Competency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_global', models.BooleanField(default=True, help_text='Si se marca, aplica a todos los empleados.', verbose_name='¿Es Global?')),
                ('job_titles', models.ManyToManyField(blank=True, related_name='specific_competencies', to='organization.jobtitle', verbose_name='Aplica a Cargos Específicos')),
            ],
            options={
                'verbose_name': 'Competencia / Criterio',
                'verbose_name_plural': 'Competencias',
            },
        ),
        migrations.CreateModel(
            name='PerformanceReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('final_score', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Promedio Final')),
                ('status', models.CharField(choices=[('BOR', 'Borrador'), ('ENV', 'Enviada / Finalizada'), ('ACE', 'Aceptada por Empleado')], default='BOR', max_length=3)),
                ('feedback_manager', models.TextField(blank=True, verbose_name='Comentarios del Jefe')),
                ('feedback_employee', models.TextField(blank=True, verbose_name='Comentarios del Empleado')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='employment.employment')),
                ('evaluator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reviews_given', to='core.person')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='performance.evaluationperiod')),
            ],
            options={
                'verbose_name': 'Evaluación de Desempeño',
                'unique_together': {('period', 'employment')},
            },
        ),
        migrations.CreateModel(
            name='ReviewDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='Puntaje (1-5)')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Observación')),
                ('competency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='performance.competency')),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='performance.performancereview')),
            ],
            options={
                'unique_together': {('review', 'competency')},
            },
        ),
    ]
