# Generated by Django 5.2.8 on 2025-11-25 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='performancereview',
            options={'verbose_name': 'Evaluación de Desempeño', 'verbose_name_plural': 'Evaluaciones de Desempeño'},
        ),
    ]
