# Generated by Django 5.2.8 on 2025-12-03 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0002_alter_performancereview_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='competency',
            name='category',
            field=models.CharField(blank=True, choices=[('CAL', 'Calidad'), ('COM', 'Compromiso'), ('CMU', 'Comunicación'), ('ORG', 'Organización'), ('DIS', 'Disciplina'), ('PRO', 'Proactividad')], db_index=True, help_text='Categoría de evaluación según la matriz de desempeño global', max_length=3, null=True, verbose_name='Categoría'),
        ),
    ]
