# Generated by Django 5.2.8 on 2025-11-26 23:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('last_name', models.CharField(max_length=100, verbose_name='Apellido')),
                ('email', models.EmailField(max_length=254, verbose_name='Correo Electrónico')),
                ('phone', models.CharField(max_length=20, verbose_name='Teléfono')),
                ('national_id', models.CharField(help_text='Documento de identidad', max_length=20, verbose_name='Cédula/ID Nacional')),
                ('cv_file', models.FileField(help_text='Archivo PDF del currículum', upload_to='candidates/cv/', verbose_name='Currículum (PDF)')),
                ('education_details', models.TextField(blank=True, help_text='Información educativa (JSON o texto)', null=True, verbose_name='Detalles de Educación')),
                ('experience_details', models.TextField(blank=True, help_text='Historial laboral (JSON o texto)', null=True, verbose_name='Detalles de Experiencia')),
                ('portfolio_url', models.URLField(blank=True, help_text='Enlace a portafolio o LinkedIn', null=True, verbose_name='URL de Portafolio')),
                ('stage', models.CharField(choices=[('NEW', 'Nuevo'), ('REV', 'En Revisión'), ('INT', 'Entrevista/Pruebas'), ('OFF', 'Oferta Enviada'), ('HIRED', 'Contratado'), ('REJ', 'Rechazado'), ('POOL', 'Banco de Elegibles')], default='NEW', max_length=5, verbose_name='Etapa')),
                ('notes', models.TextField(blank=True, help_text='Comentarios del reclutador sobre el candidato', null=True, verbose_name='Notas Internas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Candidato',
                'verbose_name_plural': 'Candidatos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CandidateEducation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(max_length=255, verbose_name='Institución')),
                ('level_name', models.CharField(help_text='Ej: Ingeniería, Licenciatura, Maestría', max_length=100, verbose_name='Nivel Educativo')),
                ('field_name', models.CharField(help_text='Ej: Informática, Administración', max_length=100, verbose_name='Área de Estudio')),
                ('start_date', models.DateField(verbose_name='Fecha de Inicio')),
                ('end_date', models.DateField(blank=True, help_text='Dejar vacío si está en curso', null=True, verbose_name='Fecha de Finalización')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='education', to='ats.candidate', verbose_name='Candidato')),
            ],
            options={
                'verbose_name': 'Educación de Candidato',
                'verbose_name_plural': 'Educación de Candidatos',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='CandidateExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255, verbose_name='Empresa')),
                ('position_title', models.CharField(max_length=200, verbose_name='Cargo')),
                ('start_date', models.DateField(verbose_name='Fecha de Inicio')),
                ('end_date', models.DateField(blank=True, help_text='Dejar vacío si es actual', null=True, verbose_name='Fecha de Finalización')),
                ('description', models.TextField(blank=True, help_text='Responsabilidades y logros', null=True, verbose_name='Descripción')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experience', to='ats.candidate', verbose_name='Candidato')),
            ],
            options={
                'verbose_name': 'Experiencia de Candidato',
                'verbose_name_plural': 'Experiencias de Candidatos',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='JobPosting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Ej: Desarrollador Frontend Senior', max_length=200, verbose_name='Título de la Vacante')),
                ('description', models.TextField(help_text='Descripción completa de la vacante', verbose_name='Descripción')),
                ('salary_range', models.CharField(blank=True, help_text='Ej: $800 - $1200 USD', max_length=100, null=True, verbose_name='Rango Salarial')),
                ('location', models.CharField(blank=True, help_text='Ej: Caracas, Venezuela / Remoto', max_length=200, null=True, verbose_name='Ubicación')),
                ('ask_education', models.BooleanField(default=False, help_text='¿El formulario debe pedir información educativa?', verbose_name='Solicitar Educación')),
                ('ask_experience', models.BooleanField(default=False, help_text='¿El formulario debe pedir experiencia laboral?', verbose_name='Solicitar Experiencia')),
                ('ask_portfolio', models.BooleanField(default=False, help_text='¿El formulario debe pedir URL de portafolio?', verbose_name='Solicitar Portafolio')),
                ('status', models.CharField(choices=[('DRAFT', 'Borrador'), ('PUBLISHED', 'Publicada'), ('CLOSED', 'Cerrada'), ('FROZEN', 'Congelada')], default='DRAFT', max_length=10, verbose_name='Estado')),
                ('published_date', models.DateField(blank=True, null=True, verbose_name='Fecha de Publicación')),
                ('closing_date', models.DateField(blank=True, null=True, verbose_name='Fecha de Cierre')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='organization.department', verbose_name='Departamento')),
                ('position', models.ForeignKey(help_text='Posición organizacional a la que corresponde', null=True, on_delete=django.db.models.deletion.SET_NULL, to='organization.position', verbose_name='Posición')),
            ],
            options={
                'verbose_name': 'Vacante',
                'verbose_name_plural': 'Vacantes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='candidate',
            name='job_posting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='ats.jobposting', verbose_name='Vacante'),
        ),
        migrations.AlterUniqueTogether(
            name='candidate',
            unique_together={('job_posting', 'email')},
        ),
    ]
