# Generated by Django 5.2.8 on 2025-11-27 03:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ats', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobposting',
            name='department',
        ),
        migrations.RemoveField(
            model_name='jobposting',
            name='salary_range',
        ),
    ]
