# Generated by Django 5.2.8 on 2025-11-27 14:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ats', '0002_remove_jobposting_department_and_more'),
        ('core', '0002_alter_personbankaccount_account_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='phone_area_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.phoneareacode', verbose_name='Código de Área'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='phone_subscriber',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Número de Suscriptor'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono (Completo)'),
        ),
    ]
