# Generated by Django 5.2.8 on 2025-11-27 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ats', '0003_add_phone_area_code_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='experience_details',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='portfolio_url',
        ),
        migrations.RemoveField(
            model_name='jobposting',
            name='ask_experience',
        ),
        migrations.RemoveField(
            model_name='jobposting',
            name='ask_portfolio',
        ),
        migrations.DeleteModel(
            name='CandidateExperience',
        ),
    ]
