# Generated by Django 5.2.8 on 2025-11-27 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ats', '0004_remove_candidate_experience_details_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='candidates/avatars/', verbose_name='Foto de Perfil'),
        ),
    ]
