# Generated by Django 5.2.8 on 2025-11-27 20:56

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ats', '0006_candidatelog'),
        ('core', '0003_historicalperson'),
        ('organization', '0002_historicaldepartment_historicalposition'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalCandidate',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('last_name', models.CharField(max_length=100, verbose_name='Apellido')),
                ('email', models.EmailField(max_length=254, verbose_name='Correo Electrónico')),
                ('phone_subscriber', models.CharField(blank=True, max_length=10, null=True, verbose_name='Número de Suscriptor')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono (Completo)')),
                ('national_id', models.CharField(help_text='Documento de identidad', max_length=20, verbose_name='Cédula/ID Nacional')),
                ('avatar', models.TextField(blank=True, max_length=100, null=True, verbose_name='Foto de Perfil')),
                ('cv_file', models.TextField(help_text='Archivo PDF del currículum', max_length=100, verbose_name='Currículum (PDF)')),
                ('education_details', models.TextField(blank=True, help_text='Información educativa (JSON o texto)', null=True, verbose_name='Detalles de Educación')),
                ('stage', models.CharField(choices=[('NEW', 'Nuevo'), ('REV', 'En Revisión'), ('INT', 'Entrevista/Pruebas'), ('OFF', 'Oferta Enviada'), ('HIRED', 'Contratado'), ('REJ', 'Rechazado'), ('POOL', 'Banco de Elegibles')], default='NEW', max_length=5, verbose_name='Etapa')),
                ('notes', models.TextField(blank=True, help_text='Comentarios del reclutador sobre el candidato', null=True, verbose_name='Notas Internas')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('job_posting', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='ats.jobposting', verbose_name='Vacante')),
                ('phone_area_code', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.phoneareacode', verbose_name='Código de Área')),
            ],
            options={
                'verbose_name': 'historical Candidato',
                'verbose_name_plural': 'historical Candidatos',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalJobPosting',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('title', models.CharField(help_text='Ej: Desarrollador Frontend Senior', max_length=200, verbose_name='Título de la Vacante')),
                ('description', models.TextField(help_text='Descripción completa de la vacante', verbose_name='Descripción')),
                ('location', models.CharField(blank=True, help_text='Ej: Caracas, Venezuela / Remoto', max_length=200, null=True, verbose_name='Ubicación')),
                ('ask_education', models.BooleanField(default=False, help_text='¿El formulario debe pedir información educativa?', verbose_name='Solicitar Educación')),
                ('status', models.CharField(choices=[('DRAFT', 'Borrador'), ('PUBLISHED', 'Publicada'), ('CLOSED', 'Cerrada'), ('FROZEN', 'Congelada')], default='DRAFT', max_length=10, verbose_name='Estado')),
                ('published_date', models.DateField(blank=True, null=True, verbose_name='Fecha de Publicación')),
                ('closing_date', models.DateField(blank=True, null=True, verbose_name='Fecha de Cierre')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('position', models.ForeignKey(blank=True, db_constraint=False, help_text='Posición organizacional a la que corresponde', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='organization.position', verbose_name='Posición')),
            ],
            options={
                'verbose_name': 'historical Vacante',
                'verbose_name_plural': 'historical Vacantes',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
