# Generated by Django 5.2.8 on 2025-11-29 20:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ats', '0007_historicalcandidate_historicaljobposting'),
        ('core', '0005_phonecarriercode_alter_phoneareacode_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='phone_area_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.phonecarriercode', verbose_name='Código de Área'),
        ),
        migrations.AlterField(
            model_name='historicalcandidate',
            name='phone_area_code',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.phonecarriercode', verbose_name='Código de Área'),
        ),
    ]
