# Generated by Django 5.2.8 on 2025-11-21 18:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmploymentStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(error_messages={'unique': 'Ya existe un registro con este nombre.'}, help_text='Ej: Activo, En Reposo, Suspendido, Finalizado', max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmploymentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(error_messages={'unique': 'Ya existe un registro con este nombre.'}, help_text='Ej: Período de Prueba, Tiempo Indefinido', max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(error_messages={'unique': 'Ya existe un registro con este nombre.'}, help_text='Manager, Supervisor, Employee', max_length=50, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Employment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hire_date', models.DateField(verbose_name='Fecha de Contratación')),
                ('end_date', models.DateField(blank=True, help_text="Fecha de fin de contrato (para 'Tiempo Determinado' o 'Prueba')", null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employments', to='core.person')),
                ('position', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employments', to='organization.position')),
                ('employment_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='employment.employmenttype')),
                ('role', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='employment.role')),
            ],
        ),
        migrations.CreateModel(
            name='EmploymentStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(help_text='Fecha de inicio de este estatus')),
                ('end_date', models.DateField(blank=True, help_text='Fecha de fin (NULL si es el estatus actual)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='employment.employment')),
                ('status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='employment.employmentstatus')),
            ],
        ),
    ]
