# Generated by Django 5.2.8 on 2025-11-24 08:15

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmploymentStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(error_messages={'unique': 'Ya existe un registro con este nombre.'}, help_text='Ej: Activo, En Reposo, Suspendido, Finalizado', max_length=50, unique=True)),
                ('is_active_relationship', models.BooleanField(default=True, help_text='Si está marcado, este estatus cuenta como que el empleado ocupa el cargo (ej: Activo, Reposo). Si no (ej: Finalizado), libera el cargo.', verbose_name='¿Es vinculación activa?')),
            ],
        ),
        migrations.CreateModel(
            name='EmploymentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(error_messages={'unique': 'Ya existe un registro con este nombre.'}, help_text='Ej: Período de Prueba, Tiempo Indefinido', max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(error_messages={'unique': 'Ya existe un registro con este nombre.'}, help_text='Manager, Supervisor, Employee', max_length=50, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Employment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exit_reason', models.CharField(blank=True, choices=[('REN', 'Renuncia Voluntaria'), ('DES', 'Despido / Cese'), ('FIN', 'Fin de Contrato (Tiempo Cumplido)'), ('JUB', 'Jubilación'), ('FAL', 'Fallecimiento'), ('OTR', 'Otro Motivo')], max_length=3, null=True, verbose_name='Motivo de Salida')),
                ('exit_notes', models.TextField(blank=True, help_text='Detalle o carta de renuncia.', null=True, verbose_name='Observaciones')),
                ('hire_date', models.DateField(verbose_name='Fecha de Contratación')),
                ('end_date', models.DateField(blank=True, help_text="Fecha de fin de contrato (para 'Tiempo Determinado' o 'Prueba')", null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employments', to='core.person', verbose_name='Colaborador')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employments', to='organization.position', verbose_name='Cargo / Posición')),
                ('current_status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='active_employments', to='employment.employmentstatus', verbose_name='Estatus Actual')),
                ('employment_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employments', to='employment.employmenttype', verbose_name='Tipo de Contrato')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employments', to='employment.role', verbose_name='Rol Funcional')),
            ],
            options={
                'verbose_name': 'Expediente Laboral',
                'ordering': ['-hire_date'],
            },
        ),
        migrations.CreateModel(
            name='EmploymentStatusLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(default=django.utils.timezone.now, help_text='Fecha de inicio de este estatus')),
                ('reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_logs', to='employment.employment')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='employment.employmentstatus')),
            ],
            options={
                'verbose_name': 'Historial de Estatus',
                'ordering': ['-created_at'],
            },
        ),
    ]
