# Generated by Django 5.2.8 on 2025-11-27 20:56

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_historicalperson'),
        ('employment', '0001_initial'),
        ('organization', '0002_historicaldepartment_historicalposition'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalEmployment',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('exit_reason', models.CharField(blank=True, choices=[('REN', 'Renuncia Voluntaria'), ('DES', 'Despido / Cese'), ('FIN', 'Fin de Contrato (Tiempo Cumplido)'), ('JUB', 'Jubilación'), ('FAL', 'Fallecimiento'), ('OTR', 'Otro Motivo')], max_length=3, null=True, verbose_name='Motivo de Salida')),
                ('exit_notes', models.TextField(blank=True, help_text='Detalle o carta de renuncia.', null=True, verbose_name='Observaciones')),
                ('hire_date', models.DateField(verbose_name='Fecha de Contratación')),
                ('end_date', models.DateField(blank=True, help_text="Fecha de fin de contrato (para 'Tiempo Determinado' o 'Prueba')", null=True)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('current_status', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='employment.employmentstatus', verbose_name='Estatus Actual')),
                ('employment_type', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='employment.employmenttype', verbose_name='Tipo de Contrato')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('person', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.person', verbose_name='Colaborador')),
                ('position', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='organization.position', verbose_name='Cargo / Posición')),
                ('role', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='employment.role', verbose_name='Rol Funcional')),
            ],
            options={
                'verbose_name': 'historical Expediente Laboral',
                'verbose_name_plural': 'historical Expediente Laborals',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
