# Generated by Django 5.2.8 on 2025-11-30 21:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employment', '0002_historicalemployment'),
    ]

    operations = [
        migrations.AddField(
            model_name='employment',
            name='current_status_new',
            field=models.CharField(choices=[('ACT', 'Activo'), ('SUS', 'Suspendido'), ('PER', 'De Permiso'), ('REP', 'Reposo'), ('FIN', 'Finalizado'), ('REN', 'Renuncia'), ('DES', 'Despido'), ('ANU', 'Anulado')], max_length=3, null=True, verbose_name='Estatus Actual'),
        ),
        migrations.AddField(
            model_name='employment',
            name='employment_type_new',
            field=models.CharField(choices=[('FIJ', 'Fijo'), ('TMP', 'Temporal'), ('PAS', 'Pasantía')], max_length=3, null=True, verbose_name='Tipo de Contrato'),
        ),
        migrations.AddField(
            model_name='employment',
            name='role_new',
            field=models.CharField(choices=[('EMP', 'Empleado'), ('MGR', 'Manager')], max_length=3, null=True, verbose_name='Rol Funcional'),
        ),
        migrations.AddField(
            model_name='historicalemployment',
            name='current_status_new',
            field=models.CharField(choices=[('ACT', 'Activo'), ('SUS', 'Suspendido'), ('PER', 'De Permiso'), ('REP', 'Reposo'), ('FIN', 'Finalizado'), ('REN', 'Renuncia'), ('DES', 'Despido'), ('ANU', 'Anulado')], max_length=3, null=True, verbose_name='Estatus Actual'),
        ),
        migrations.AddField(
            model_name='historicalemployment',
            name='employment_type_new',
            field=models.CharField(choices=[('FIJ', 'Fijo'), ('TMP', 'Temporal'), ('PAS', 'Pasantía')], max_length=3, null=True, verbose_name='Tipo de Contrato'),
        ),
        migrations.AddField(
            model_name='historicalemployment',
            name='role_new',
            field=models.CharField(choices=[('EMP', 'Empleado'), ('MGR', 'Manager')], max_length=3, null=True, verbose_name='Rol Funcional'),
        ),
        migrations.AlterField(
            model_name='employment',
            name='current_status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='active_employments', to='employment.employmentstatus', verbose_name='Estatus Actual (Old)'),
        ),
        migrations.AlterField(
            model_name='employment',
            name='employment_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='employments', to='employment.employmenttype', verbose_name='Tipo de Contrato (Old)'),
        ),
        migrations.AlterField(
            model_name='employment',
            name='role',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='employments', to='employment.role', verbose_name='Rol Funcional (Old)'),
        ),
        migrations.AlterField(
            model_name='historicalemployment',
            name='current_status',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='employment.employmentstatus', verbose_name='Estatus Actual (Old)'),
        ),
        migrations.AlterField(
            model_name='historicalemployment',
            name='employment_type',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='employment.employmenttype', verbose_name='Tipo de Contrato (Old)'),
        ),
        migrations.AlterField(
            model_name='historicalemployment',
            name='role',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='employment.role', verbose_name='Rol Funcional (Old)'),
        ),
    ]
