# Generated by Django 5.2.8 on 2025-11-30 21:36

from django.db import migrations


def migrate_to_choices(apps, schema_editor):
    """
    Copia los datos de los ForeignKey a los nuevos campos CharField con choices.
    Mapea los nombres de los catálogos a los códigos de choices.
    """
    Employment = apps.get_model('employment', 'Employment')
    
    # Mapeos de nombre a código de choice
    role_map = {
        'Empleado': 'EMP',
        'Manager': 'MGR',
    }
    
    type_map = {
        'Fijo': 'FIJ',
        'Temporal': 'TMP',
        'Pasantía': 'PAS',
    }
    
    status_map = {
        'Activo': 'ACT',
        'Suspendido': 'SUS',
        'De Permiso': 'PER',
        'Reposo': 'REP',
        'Finalizado': 'FIN',
        'Renuncia': 'REN',
        'Despido': 'DES',
        'Anulado': 'ANU',
    }
    
    for employment in Employment.objects.all():
        # Migrar role
        if employment.role:
            employment.role_new = role_map.get(employment.role.name, 'EMP')
        
        # Migrar employment_type
        if employment.employment_type:
            employment.employment_type_new = type_map.get(employment.employment_type.name, 'FIJ')
        
        # Migrar current_status
        if employment.current_status:
            employment.current_status_new = status_map.get(employment.current_status.name, 'ACT')
        
        employment.save()


def reverse_migrate(apps, schema_editor):
    """
    Rollback: Copiar de vuelta los valores de choice a los FK.
    Esto solo funciona si los catálogos aún existen.
    """
    Employment = apps.get_model('employment', 'Employment')
    Role = apps.get_model('employment', 'Role')
    EmploymentType = apps.get_model('employment', 'EmploymentType')
    EmploymentStatus = apps.get_model('employment', 'EmploymentStatus')
    
    # Mapeos inversos de código a nombre
    role_reverse = {
        'EMP': 'Empleado',
        'MGR': 'Manager',
    }
    
    type_reverse = {
        'FIJ': 'Fijo',
        'TMP': 'Temporal',
        'PAS': 'Pasantía',
    }
    
    status_reverse = {
        'ACT': 'Activo',
        'SUS': 'Suspendido',
        'PER': 'De Permiso',
        'REP': 'Reposo',
        'FIN': 'Finalizado',
        'REN': 'Renuncia',
        'DES': 'Despido',
        'ANU': 'Anulado',
    }
    
    for employment in Employment.objects.all():
        # Restaurar role
        if employment.role_new:
            role_name = role_reverse.get(employment.role_new)
            if role_name:
                employment.role = Role.objects.filter(name=role_name).first()
        
        # Restaurar employment_type
        if employment.employment_type_new:
            type_name = type_reverse.get(employment.employment_type_new)
            if type_name:
                employment.employment_type = EmploymentType.objects.filter(name=type_name).first()
        
        # Restaurar current_status
        if employment.current_status_new:
            status_name = status_reverse.get(employment.current_status_new)
            if status_name:
                employment.current_status = EmploymentStatus.objects.filter(name=status_name).first()
        
        employment.save()


class Migration(migrations.Migration):

    dependencies = [
        ('employment', '0003_add_choice_fields'),
    ]

    operations = [
        migrations.RunPython(migrate_to_choices, reverse_migrate),
    ]
