# Generated by Django 5.2.8 on 2025-11-30 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employment', '0004_migrate_data_to_choices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employmentstatuslog',
            name='status',
            field=models.CharField(choices=[('ACT', 'Activo'), ('SUS', 'Suspendido'), ('PER', 'De Permiso'), ('REP', 'Reposo'), ('FIN', 'Finalizado'), ('REN', 'Renuncia'), ('DES', 'Despido'), ('ANU', 'Anulado')], max_length=3, verbose_name='Estatus'),
        ),
        migrations.AlterField(
            model_name='historicalemployment',
            name='current_status',
            field=models.CharField(choices=[('ACT', 'Activo'), ('SUS', 'Suspendido'), ('PER', 'De Permiso'), ('REP', 'Reposo'), ('FIN', 'Finalizado'), ('REN', 'Renuncia'), ('DES', 'Despido'), ('ANU', 'Anulado')], default='ACT', max_length=3, verbose_name='Estatus Actual'),
        ),
        migrations.AlterField(
            model_name='employment',
            name='current_status',
            field=models.CharField(choices=[('ACT', 'Activo'), ('SUS', 'Suspendido'), ('PER', 'De Permiso'), ('REP', 'Reposo'), ('FIN', 'Finalizado'), ('REN', 'Renuncia'), ('DES', 'Despido'), ('ANU', 'Anulado')], default='ACT', max_length=3, verbose_name='Estatus Actual'),
        ),
        migrations.AlterField(
            model_name='historicalemployment',
            name='employment_type',
            field=models.CharField(choices=[('FIJ', 'Fijo'), ('TMP', 'Temporal'), ('PAS', 'Pasantía')], default='FIJ', max_length=3, verbose_name='Tipo de Contrato'),
        ),
        migrations.AlterField(
            model_name='employment',
            name='employment_type',
            field=models.CharField(choices=[('FIJ', 'Fijo'), ('TMP', 'Temporal'), ('PAS', 'Pasantía')], default='FIJ', max_length=3, verbose_name='Tipo de Contrato'),
        ),
        migrations.AlterField(
            model_name='historicalemployment',
            name='role',
            field=models.CharField(choices=[('EMP', 'Empleado'), ('MGR', 'Manager')], default='EMP', max_length=3, verbose_name='Rol Funcional'),
        ),
        migrations.AlterField(
            model_name='employment',
            name='role',
            field=models.CharField(choices=[('EMP', 'Empleado'), ('MGR', 'Manager')], default='EMP', max_length=3, verbose_name='Rol Funcional'),
        ),
        migrations.RemoveField(
            model_name='employment',
            name='current_status_new',
        ),
        migrations.RemoveField(
            model_name='employment',
            name='employment_type_new',
        ),
        migrations.RemoveField(
            model_name='employment',
            name='role_new',
        ),
        migrations.RemoveField(
            model_name='historicalemployment',
            name='current_status_new',
        ),
        migrations.RemoveField(
            model_name='historicalemployment',
            name='employment_type_new',
        ),
        migrations.RemoveField(
            model_name='historicalemployment',
            name='role_new',
        ),
        migrations.DeleteModel(
            name='EmploymentStatus',
        ),
        migrations.DeleteModel(
            name='EmploymentType',
        ),
        migrations.DeleteModel(
            name='Role',
        ),
    ]
