# Generated by Django 5.2.8 on 2025-12-01 00:47

import django.db.models.deletion
import django.utils.timezone
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_refine_validations'),
        ('employment', '0006_historicalemploymentdepartmentrole_and_more'),
        ('organization', '0008_historicalposition_objective_position_objective_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalPersonDepartmentRole',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('hierarchical_role', models.CharField(choices=[('MGR', 'Gerente'), ('EMP', 'Empleado')], default='EMP', help_text='Rol dentro del departamento (Gerente o Empleado)', max_length=3, verbose_name='Rol Jerárquico')),
                ('start_date', models.DateField(default=django.utils.timezone.now, help_text='Inicio del rol jerárquico en este departamento', verbose_name='Fecha de Inicio')),
                ('end_date', models.DateField(blank=True, help_text='Fin del rol jerárquico (NULL si es actual)', null=True, verbose_name='Fecha de Fin')),
                ('notes', models.TextField(blank=True, help_text='Observaciones sobre la asignación del rol', null=True, verbose_name='Notas')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('department', models.ForeignKey(blank=True, db_constraint=False, help_text='Departamento en el que ejerce este rol', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='organization.department', verbose_name='Departamento')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('person', models.ForeignKey(blank=True, db_constraint=False, help_text='Persona que ejerce este rol jerárquico', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.person', verbose_name='Persona')),
            ],
            options={
                'verbose_name': 'historical Rol Jerárquico por Persona',
                'verbose_name_plural': 'historical Roles Jerárquicos por Persona',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='PersonDepartmentRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hierarchical_role', models.CharField(choices=[('MGR', 'Gerente'), ('EMP', 'Empleado')], default='EMP', help_text='Rol dentro del departamento (Gerente o Empleado)', max_length=3, verbose_name='Rol Jerárquico')),
                ('start_date', models.DateField(default=django.utils.timezone.now, help_text='Inicio del rol jerárquico en este departamento', verbose_name='Fecha de Inicio')),
                ('end_date', models.DateField(blank=True, help_text='Fin del rol jerárquico (NULL si es actual)', null=True, verbose_name='Fecha de Fin')),
                ('notes', models.TextField(blank=True, help_text='Observaciones sobre la asignación del rol', null=True, verbose_name='Notas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(help_text='Departamento en el que ejerce este rol', on_delete=django.db.models.deletion.CASCADE, related_name='person_roles', to='organization.department', verbose_name='Departamento')),
                ('person', models.ForeignKey(help_text='Persona que ejerce este rol jerárquico', on_delete=django.db.models.deletion.CASCADE, related_name='department_roles', to='core.person', verbose_name='Persona')),
            ],
            options={
                'verbose_name': 'Rol Jerárquico por Persona',
                'verbose_name_plural': 'Roles Jerárquicos por Persona',
                'ordering': ['-start_date'],
                'unique_together': {('person', 'department', 'start_date')},
            },
        ),
    ]
