# Generated by Django 5.2.8 on 2025-11-24 08:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddressType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(error_messages={'unique': 'Ya existe un registro con este nombre.'}, max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(error_messages={'unique': 'Ya existe un registro con este nombre.'}, max_length=100, unique=True)),
                ('code', models.CharField(error_messages={'unique': 'Ya existe un registro con este código.'}, max_length=4, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='BankAccountType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(error_messages={'unique': 'Ya existe un registro con este nombre.'}, max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(error_messages={'unique': 'Ya existe un registro con este nombre.'}, max_length=100, unique=True)),
                ('iso_2', models.CharField(error_messages={'unique': 'Ya existe un registro con este código ISO.'}, help_text='Ej: US, VE.', max_length=2, unique=True)),
                ('phone_prefix', models.CharField(error_messages={'unique': 'Ya existe un país con este prefijo.'}, help_text='Prefijo telefónico (ej: +58).', max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='DisabilityGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(error_messages={'unique': 'Ya existe un registro con este nombre.'}, max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='DisabilityStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(error_messages={'unique': 'Ya existe un registro con este nombre.'}, max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='DisabilityType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(error_messages={'unique': 'Ya existe un registro con este nombre.'}, max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmailType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(error_messages={'unique': 'Ya existe un registro con este nombre.'}, max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(error_messages={'unique': 'Ya existe un registro con este nombre.'}, max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='MaritalStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(error_messages={'unique': 'Ya existe un registro con este nombre.'}, max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('second_name', models.CharField(blank=True, max_length=100, null=True)),
                ('paternal_surname', models.CharField(max_length=100)),
                ('maternal_surname', models.CharField(blank=True, max_length=100, null=True)),
                ('birthdate', models.DateField(blank=True, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photos/person/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('country_of_birth', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.country')),
                ('gender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.gender')),
                ('marital_status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.maritalstatus')),
            ],
        ),
        migrations.CreateModel(
            name='PhoneCarrier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(error_messages={'unique': 'Ya existe un registro con este nombre.'}, max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PhoneType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(error_messages={'unique': 'Ya existe un registro con este nombre.'}, max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='RelationshipType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(error_messages={'unique': 'Ya existe un registro con este nombre.'}, max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Salutation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(error_messages={'unique': 'Ya existe un registro con este nombre.'}, max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PersonBankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.CharField(max_length=20, unique=True)),
                ('is_primary', models.BooleanField(default=False)),
                ('bank', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.bank')),
                ('bank_account_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.bankaccounttype')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_accounts', to='core.person')),
            ],
        ),
        migrations.CreateModel(
            name='PersonDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='documents/person/')),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='core.person')),
            ],
        ),
        migrations.CreateModel(
            name='PersonEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_address', models.EmailField(error_messages={'unique': 'Este correo electrónico ya está registrado.'}, max_length=254, unique=True)),
                ('is_primary', models.BooleanField(default=False)),
                ('email_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.emailtype')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emails', to='core.person')),
            ],
        ),
        migrations.CreateModel(
            name='PhoneAreaCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=5)),
                ('type', models.CharField(max_length=20)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.country')),
                ('carrier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.phonecarrier')),
            ],
            options={
                'unique_together': {('country', 'code', 'carrier')},
            },
        ),
        migrations.CreateModel(
            name='EmergencyContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('second_name', models.CharField(blank=True, max_length=100, null=True)),
                ('paternal_surname', models.CharField(max_length=100)),
                ('maternal_surname', models.CharField(blank=True, max_length=100, null=True)),
                ('phone_number', models.CharField(max_length=10)),
                ('is_primary', models.BooleanField(default=False)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emergency_contacts', to='core.person')),
                ('phone_area_code', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.phoneareacode')),
                ('relationship', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.relationshiptype')),
            ],
        ),
        migrations.AddField(
            model_name='person',
            name='salutation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.salutation'),
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.country')),
            ],
            options={
                'unique_together': {('country', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100)),
                ('postal_code', models.CharField(blank=True, max_length=20, null=True)),
                ('street_name_and_number', models.CharField(max_length=255)),
                ('extra_address_line', models.CharField(blank=True, max_length=255, null=True)),
                ('house_number', models.CharField(blank=True, max_length=50, null=True)),
                ('apartment', models.CharField(blank=True, max_length=50, null=True)),
                ('street_2', models.CharField(blank=True, max_length=255, null=True)),
                ('address_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.addresstype')),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.country')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='core.person')),
                ('state', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.state')),
            ],
        ),
        migrations.CreateModel(
            name='PersonDisabilityVE',
            fields=[
                ('person', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='core.person')),
                ('date_learned', models.DateField(blank=True, null=True)),
                ('disability_degree', models.CharField(blank=True, max_length=50, null=True)),
                ('issuing_authority', models.CharField(blank=True, max_length=100, null=True)),
                ('reference_number', models.CharField(blank=True, max_length=50, null=True)),
                ('date_of_determination', models.DateField(blank=True, null=True)),
                ('disability_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.disabilitygroup')),
                ('disability_status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.disabilitystatus')),
                ('disability_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.disabilitytype')),
            ],
        ),
        migrations.CreateModel(
            name='NationalId',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('CEDULA', 'Cédula de Identidad'), ('RIF', 'RIF'), ('PASSPORT', 'Pasaporte')], default='CEDULA', max_length=10)),
                ('document_type', models.CharField(choices=[('V', 'V - Venezolano / Persona Natural'), ('E', 'E - Extranjero / Persona Natural'), ('J', 'J - Jurídico'), ('G', 'G - Gubernamental'), ('P', 'P - Pasaporte')], default='V', max_length=1, verbose_name='Prefijo')),
                ('number', models.CharField(help_text='Solo números.', max_length=20)),
                ('is_primary', models.BooleanField(default=False)),
                ('file', models.FileField(blank=True, null=True, upload_to='documents/national_id/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='national_ids', to='core.person')),
            ],
            options={
                'unique_together': {('document_type', 'number'), ('person', 'category')},
            },
        ),
        migrations.CreateModel(
            name='PersonNationality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.country')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nationalities', to='core.person')),
            ],
            options={
                'unique_together': {('person', 'country')},
            },
        ),
        migrations.CreateModel(
            name='PersonPhone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscriber_number', models.CharField(max_length=10)),
                ('is_primary', models.BooleanField(default=False)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phones', to='core.person')),
                ('area_code', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.phoneareacode')),
                ('phone_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.phonetype')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('area_code', 'subscriber_number'), name='phone_unique', violation_error_message='Este número de teléfono ya se encuentra registrado.'), models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('person',), name='one_primary_phone_per_person', violation_error_message='La persona ya tiene un teléfono principal registrado.')],
            },
        ),
        migrations.CreateModel(
            name='Dependent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('second_name', models.CharField(blank=True, max_length=100, null=True)),
                ('paternal_surname', models.CharField(max_length=100)),
                ('maternal_surname', models.CharField(blank=True, max_length=100, null=True)),
                ('birthdate', models.DateField()),
                ('gender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.gender')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependents', to='core.person')),
                ('relationship', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.relationshiptype')),
            ],
            options={
                'unique_together': {('person', 'first_name', 'paternal_surname')},
            },
        ),
    ]
