# Generated by Django 5.2.8 on 2025-11-22 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personemail',
            name='email_address',
            field=models.EmailField(error_messages={'unique': 'Este correo electrónico ya está registrado.'}, max_length=254, unique=True),
        ),
        migrations.AddConstraint(
            model_name='personphone',
            constraint=models.UniqueConstraint(fields=('area_code', 'subscriber_number'), name='phone_unique', violation_error_message='Este número de teléfono ya se encuentra registrado.'),
        ),
        migrations.AddConstraint(
            model_name='personphone',
            constraint=models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('person',), name='one_primary_phone_per_person', violation_error_message='La persona ya tiene un teléfono principal registrado.'),
        ),
    ]
