# Generated by Django 5.2.8 on 2025-11-26 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personbankaccount',
            name='account_number',
            field=models.CharField(error_messages={'unique': 'Este número de cuenta ya está registrado.'}, max_length=20, unique=True),
        ),
    ]
