# Generated by Django 5.2.8 on 2025-11-22 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_personemail_email_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personemail',
            name='email_address',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AddConstraint(
            model_name='personemail',
            constraint=models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('person',), name='one_primary_email_per_person', violation_error_message='La persona ya tiene un correo electrónico principal registrado.'),
        ),
        migrations.AlterModelTable(
            name='personemail',
            table='person_email',
        ),
    ]
