# Generated by Django 5.2.8 on 2025-11-22 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_personemail_email_address_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='personemail',
            name='one_primary_email_per_person',
        ),
        migrations.AlterField(
            model_name='personemail',
            name='email_address',
            field=models.EmailField(error_messages={'unique': 'Este correo electrónico ya está registrado.'}, max_length=254, unique=True),
        ),
        migrations.AlterModelTable(
            name='personemail',
            table=None,
        ),
    ]
