# Generated by Django 5.2.8 on 2025-11-27 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_historicalperson'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country',
            name='phone_prefix',
        ),
    ]
