# Generated by Django 5.2.8 on 2025-11-29 20:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_phone_prefix'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneCarrierCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=5)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='phoneareacode',
            unique_together=None,
        ),
        # IMPORTANT: Remove constraint BEFORE removing fields it references
        migrations.RemoveConstraint(
            model_name='personphone',
            name='phone_unique',
        ),
        migrations.RemoveField(
            model_name='phoneareacode',
            name='carrier',
        ),
        migrations.RemoveField(
            model_name='phoneareacode',
            name='country',
        ),
        migrations.RemoveField(
            model_name='personphone',
            name='area_code',
        ),
        migrations.RemoveField(
            model_name='emergencycontact',
            name='phone_area_code',
        ),
        migrations.AddField(
            model_name='phonecarriercode',
            name='carrier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.phonecarrier'),
        ),
        migrations.AddField(
            model_name='emergencycontact',
            name='phone_carrier_code',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.phonecarriercode'),
        ),
        migrations.AddField(
            model_name='personphone',
            name='carrier_code',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.phonecarriercode'),
        ),
        migrations.AddConstraint(
            model_name='personphone',
            constraint=models.UniqueConstraint(fields=('carrier_code', 'subscriber_number'), name='phone_unique', violation_error_message='Este número de teléfono ya se encuentra registrado.'),
        ),
    ]
