# Generated by Django 5.2.8 on 2025-11-29 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ats', '0008_alter_candidate_phone_area_code_and_more'),
        ('core', '0005_phonecarriercode_alter_phoneareacode_unique_together_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PhoneAreaCode',
        ),
        migrations.AlterUniqueTogether(
            name='phonecarriercode',
            unique_together={('carrier', 'code')},
        ),
    ]
