# Generated by Django 5.2.8 on 2025-11-30 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_delete_phoneareacode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phonecarriercode',
            name='code',
            field=models.CharField(max_length=4),
        ),
    ]
