# Generated by Django 5.2.8 on 2025-12-01 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_make_gender_birthdate_required'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalperson',
            name='birthdate',
            field=models.DateField(),
        ),
    ]
