# Generated by Django 5.2.8 on 2025-12-07 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_historicalperson_birthdate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalperson',
            name='cv_file',
            field=models.TextField(blank=True, help_text='Curriculum Vitae (PDF, DOCX)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='cv_file',
            field=models.FileField(blank=True, help_text='Curriculum Vitae (PDF, DOCX)', null=True, upload_to='cv/person/'),
        ),
    ]
